/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fpoly.tn.gd;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;

/**
 *
 * @author TRINH THE NAM
 */
public class frm_Loading extends javax.swing.JFrame {

    /**
     * Creates new form frm_Loading
     */
    public frm_Loading() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setBackground(new Color(0, 0, 0, 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_loadding = new javax.swing.JPanel();
        lbl_texthello = new javax.swing.JLabel();
        probLoading = new javax.swing.JProgressBar();
        lbl_textload = new javax.swing.JLabel();
        lbl_backgroung_loadding = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(785, 500));
        setMinimumSize(new java.awt.Dimension(785, 500));
        setUndecorated(true);
        getContentPane().setLayout(null);

        pnl_loadding.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnl_loadding);
        pnl_loadding.setBounds(0, 0, 0, 0);

        lbl_texthello.setFont(new java.awt.Font("UTM Alba Matter", 0, 24)); // NOI18N
        lbl_texthello.setForeground(new java.awt.Color(255, 255, 255));
        lbl_texthello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_texthello.setText("\"HELLO\"");
        getContentPane().add(lbl_texthello);
        lbl_texthello.setBounds(270, 380, 250, 50);

        probLoading.setBackground(new java.awt.Color(255, 255, 255));
        probLoading.setForeground(new java.awt.Color(49, 238, 252));
        getContentPane().add(probLoading);
        probLoading.setBounds(50, 450, 700, 30);

        lbl_textload.setFont(new java.awt.Font("UTM Alba Matter", 0, 24)); // NOI18N
        lbl_textload.setForeground(new java.awt.Color(255, 255, 255));
        lbl_textload.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_textload.setText("0");
        getContentPane().add(lbl_textload);
        lbl_textload.setBounds(270, 350, 250, 40);

        lbl_backgroung_loadding.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledForeground"));
        lbl_backgroung_loadding.setFont(new java.awt.Font("UTM Cookies", 0, 36)); // NOI18N
        lbl_backgroung_loadding.setForeground(new java.awt.Color(255, 255, 255));
        lbl_backgroung_loadding.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_backgroung_loadding.setFocusCycleRoot(true);
        getContentPane().add(lbl_backgroung_loadding);
        lbl_backgroung_loadding.setBounds(0, 0, 790, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        frm_Loading Splash = new frm_Loading();
        Splash.setVisible(true);
        frm_QuanLy lognIn = new frm_QuanLy();

        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(40);
                Splash.lbl_textload.setText(Integer.toString(i) + "%");
                Splash.probLoading.setValue(i);
                Splash.lbl_texthello.setText("loading...");
                Splash.lbl_texthello.setForeground(new Color(255, 255, 255));
                int dem = 0;
                dem = dem + i;
                Splash.probLoading.setBorder(null);
                if (i == 100) {
                    Splash.lbl_texthello.setFont(new Font("UTM Alba Matter", Font.PLAIN, 30));
                    Splash.lbl_texthello.setText("welcome");
                    Splash.lbl_texthello.setForeground(new Color(255, 255, 255));
                    for (int ii = 0; true; ii++) {
                        dem = dem + ii;
                        if (dem == 200) {
                            Splash.dispose();
                            lognIn.setVisible(true);
                            break;
                        }
                    }
                }
                
            }
        } catch (Exception ex) {
            System.out.println("Lổi Loadding Đăng Nhập");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_backgroung_loadding;
    private javax.swing.JLabel lbl_texthello;
    private javax.swing.JLabel lbl_textload;
    private javax.swing.JPanel pnl_loadding;
    private javax.swing.JProgressBar probLoading;
    // End of variables declaration//GEN-END:variables
}
